implementation/ICT/ICT.MM.PL.WebAPI/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security;
using ICT.MM.DAL.DB;
using System.Web.Http;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using ActionNameAttribute = Microsoft.AspNetCore.Mvc.ActionNameAttribute;
using Microsoft.AspNetCore.Authorization.Policy;
using Microsoft.AspNetCore.Authorization;
using AuthorizeAttribute = Microsoft.AspNetCore.Authorization.AuthorizeAttribute;

namespace ICT.MM.PL.WebAPI.Controllers
{
    /// <summary>
    /// Controller para os devices
    /// </summary>
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize(Policy = "LoggedIn")]
    public class DevicesController : Controller
    {
        //variavel de acesso a base de dados
        private readonly ICTDbContext _context;

        public DevicesController(ICTDbContext context)
        {
            _context = context;
        }

        // GET: Devices
        /// <summary>
        /// Lista os dispositivos presentes na base de dados
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var iCTDbContext = _context.Devices.Include(d => d.DeviceType);

            return View(await iCTDbContext.ToListAsync());
        }
        /// <summary>
        /// Retorna a view com os detalhes de um dispositivo, dando o id do device 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Devices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }
            //procura na base de dados pelo dispositivo
            var device = await _context.Devices
                .Include(d => d.DeviceType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        /// <summary>
        /// Retorna a view para criar um novo dispositivo
        /// </summary>
        /// <returns></returns>
        // GET: Devices/Create
        [Authorize(Policy = "Admin")]
        public IActionResult Create()
        {
            //envia para a view a lista de todos os tipos de dispositivos para o utilizador poder selecionar o tipo de dispositivo correto de entre os que existem na base de dados
            ViewData["Id_DeviceType"] = new SelectList(_context.DeviceTypes, "Id", "Name");
            return View();
        }
        /// <summary>
        /// Cria na base de dados um novo dispositivo dispositivo 
        /// </summary>
        /// <param name="device"></param>
        /// <returns></returns>
        // POST: Devices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Id_DeviceType,Name,Description,ManufacturedDate,LastMaintenanceDate,MaintenanceDueDate,ManufacturedBy,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] Device device)
        {
            if (ModelState.IsValid)
            {
                //alguma atribuições basicas
                device.LastMaintenanceDate = null;
                device.ModifiedDate = null;
                device.ModifiedBy = null;
                device.CreatedDate = DateTime.Now;
                device.CreatedBy = User.Identity.Name;
                //guardar na base de dados
                _context.Add(device);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_DeviceType"] = new SelectList(_context.DeviceTypes, "Id", "Name", device.Id_DeviceType);
            return View(device);
        }
        /// <summary>
        /// retorna a view para editar um dispositivo dando o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Devices/Edit/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }
            //procura na base de dados o dispositivo
            var device = await _context.Devices.FindAsync(id);
            if (device == null)
            {
                return NotFound();
            }
            ViewData["Id_DeviceType"] = new SelectList(_context.DeviceTypes, "Id", "Name", device.Id_DeviceType);
            return View(device);
        }
        /// <summary>
        /// Guarda na base de dados as alterações realizadas ao dispositivo
        /// </summary>
        /// <param name="id"></param>
        /// <param name="device"></param>
        /// <returns></returns>
        // POST: Devices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Id_DeviceType,Name,Description,ManufacturedDate,LastMaintenanceDate,MaintenanceDueDate,ManufacturedBy,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] Device device)
        {
            //faz se algumas verificações para editar o dispositivo
            if (id != device.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                
                try
                {
                    //Algumas atribuições simples
                    device.ModifiedDate = DateTime.Now;
                    device.ModifiedBy = User.Identity.Name;
                    //guardas as alterações na base de dados
                    _context.Update(device);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceExists(device.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_DeviceType"] = new SelectList(_context.DeviceTypes, "Id", "Name", device.Id_DeviceType);
            return View(device);
        }
        /// <summary>
        /// Retorna a view para se confirmar a eliminiação de um dispositivo
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Devices/Delete/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }
            //procura na base de dados o dispositivo
            var device = await _context.Devices
                .Include(d => d.DeviceType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }
        /// <summary>
        /// Elimina um dispositivo da base de dados
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Devices == null)
            {
                return Problem("Entity set 'ICTDbContext.Devices'  is null.");
            }
            //procura na base de dados o dipositivo e se exitir elimina-o da base de dados
            var device = await _context.Devices.FindAsync(id);
            if (device != null)
            {
                _context.Devices.Remove(device);
            }
            //procura na base de dados por ScenarioDevice que possuam como id_Device o id desse device e elimina os a todos 
            var scenarioDevices = _context.ScenarioDevices.Where(m => m.Id_Device == id);

            if (scenarioDevices != null)
            {
                _context.ScenarioDevices.RemoveRange(scenarioDevices);
            }
            //guarda as alterações da base de dados
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// Verifica se um dispositivo existe dado o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool DeviceExists(int id)
        {
          return (_context.Devices?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

implementation/ICT/ICT.MM.PL.WebAPI/Controllers/ScenariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT.MM.DAL.DB;
using Microsoft.AspNetCore.Authorization;

namespace ICT.MM.PL.WebAPI.Controllers
{
    /// <summary>
    /// Controller para os Cenarios
    /// </summary>
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize(Policy = "LoggedIn")]
    public class ScenariosController : Controller
    {
        private readonly ICTDbContext _context;

        public ScenariosController(ICTDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Lista todos os cenarios presentes na base de dados
        /// </summary>
        /// <returns></returns>
        // GET: Scenarios
        public async Task<IActionResult> Index()
        {
              return _context.Scenarios != null ? 
                          View(await _context.Scenarios.ToListAsync()) :
                          Problem("Entity set 'ICTDbContext.Scenarios'  is null.");
        }
        /// <summary>
        /// Retorna a View com os detalhes de um cenario dado o id do cenario
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Scenarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Scenarios == null)
            {
                return NotFound();
            }
            //procura na base de dados pelo cenario e retorna a view com os detalhe de um cenario
            var scenario = await _context.Scenarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scenario == null)
            {
                return NotFound();
            }

            return View(scenario);
        }
        /// <summary>
        /// Retorna a view para criar um novo Scenario
        /// </summary>
        /// <returns></returns>
        // GET: Scenarios/Create
        [Authorize(Policy = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Adiciona a base de dados um novo cenario
        /// </summary>
        /// <param name="scenario"></param>
        /// <returns></returns>
        // POST: Scenarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Scenario scenario)
        {
            if (ModelState.IsValid)
            {
                //adiciona e guarda um cenario na base de dados
                _context.Add(scenario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(scenario);
        }
        /// <summary>
        /// Retorna a view para editar um cenario
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Scenarios/Edit/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Scenarios == null)
            {
                return NotFound();
            }
            //procura na base de dados pelo scenario e retorna a view com esses dados
            var scenario = await _context.Scenarios.FindAsync(id);
            if (scenario == null)
            {
                return NotFound();
            }
            return View(scenario);
        }
        /// <summary>
        /// Atualiza um Cenario na base de dados
        /// </summary>
        /// <param name="id"></param>
        /// <param name="scenario"></param>
        /// <returns></returns>
        // POST: Scenarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Scenario scenario)
        {
            if (id != scenario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //atualiza o scenario na base de dados 
                    _context.Update(scenario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScenarioExists(scenario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scenario);
        }
        /// <summary>
        /// Retorna a view para o utilizador confirmar a eliminação de um cenario
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Scenarios/Delete/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Scenarios == null)
            {
                return NotFound();
            }
            //procura na base de dados e retorna a view com os dados do cenario a eliminar
            var scenario = await _context.Scenarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scenario == null)
            {
                return NotFound();
            }

            return View(scenario);
        }
        /// <summary>
        /// Elimina da base de dados um scenario dado o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Scenarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Scenarios == null)
            {
                return Problem("Entity set 'ICTDbContext.Scenarios'  is null.");
            }
            //procura na base de dados e elimina o scenario
            var scenario = await _context.Scenarios.FindAsync(id);
            if (scenario != null)
            {
                _context.Scenarios.Remove(scenario);
            }
            //procura e eliminar da base de dados todos os scenarioDevice que tenham como id de cenario o id do cenario a eliminar
            var scenarioDevices = _context.ScenarioDevices.Where(m => m.Id_Scenario == id);

            if (scenarioDevices != null)
            {
                _context.ScenarioDevices.RemoveRange(scenarioDevices);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// Verifica se um scenario existe dado o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool ScenarioExists(int id)
        {
          return (_context.Scenarios?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

implementation/ICT/ICT.MM.PL.WebAPI/Views/Shared/About.cshtml
@{

    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<style>
    .split {
        height: 92%;
        width: 40%;
        position: fixed;
        z-index: 1;
        top: 8%;
        overflow-x: hidden;
        padding-top: 20px;
    }

    /* Control the left side */
    .left {
        left: 0;
        background-color: #111;
        color:white;
    }

    /* Control the right side */
    .right {
        right: 0;
        background-color: red;
        color:black;
    }

    .centerinfo {
        font-size: 14px;
        position: absolute;
        top: 35%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
    }
    /* If you want the content centered horizontally and vertically */
    .centered {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
    }

        /* Style the image inside the centered container, if needed */
        .centered img {
            width: 150px;
            border-radius: 50%;
        }
</style>


<html>
<head>
    <title>Sobre</title>
</head>
<body>
    <div class="split left">
        <div class="centered">
            <img src="https://cdn.discordapp.com/attachments/780835143497678868/1020723366560288778/20220503_213820.jpg" alt="Vasco Araújo">
            <h2>Vasco Araújo</h2>
            <p>aluno23055@ipt.pt</p>
            <a class="nav-link" href="https://github.com/vasco2001" target="_blank" >GitHub</a>
        </div>
    </div>
    <div class="centerinfo">
        <img width="200px" src="https://cdn.discordapp.com/attachments/780835143497678868/1020730140445126666/download.png" alt="IPT">
        <br />
        <br />
        <br />
        <br />
        <strong>
            Licenciatura em <br />
            Engenharia Informática
            <br /><br /><br />Desenvolvido no âmbito
            <br />de<br />Desenvolvimento Web
            <br /><br /><br />
            Utilizadores:<br />
            <table>
                <tr>
                    <th>Nome de Utilizador</th>
                    <th>Password</th>
                </tr>
                <tr>
                    <td>User</td>
                    <td>!"#User123</td>
                </tr
                <tr>
                    <td>Admin</td>
                    <td>!"#Admin123</td>
                </tr>
                <tr>
                    <td>Root</td>
                    <td>!"#Root123</td>
                </tr>
            </table>
            <br /><br /><br />
            <a class="nav-link" asp-controller="Home" asp-action="Credits">Créditos e Referências</a>
    </div>

    <div class="split right">
        <div class="centered">
            <img src="https://cdn.discordapp.com/attachments/780835143497678868/1020724011124134001/20220917_165215.jpg" alt="André Almeida">
            <h2>André Almeida</h2>
            <p>aluno23049@ipt.pt</p>
            <a class="nav-link" href="https://github.com/JKZ02" target="_blank">GitHub</a>
        </div>
    </div>
<</body>
</html>

implementation/ICT/ICT.MM.PL.WebAPI/Views/Shared/Credits.cshtml
@{

    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<html>
<head>
    <title>Créditos e Referências</title>
</head>
<body>
    <ul>
        <li>
            <a href="https://www.youtube.com/watch?v=2yEiwjUEZ78">Método utilizado para Password hashing</a>
        </li>
    </ul>
</body>
</html>

implementation/ICT/ICT.MM.PL.WebAPI/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SOA for Safety</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet" />
</head>


<body>


    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SOA for Safety</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <div class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="About">Sobre</a>
                        </li>
                    </div>
                    <div class="navbar-text">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div style="float:left">
                                <p class="nav-link text-dark" style="padding-right:10px; padding-top:7px">Olá, @User.Identity.Name</p>
                            </div>
                        }
                        <div class="dropdown" style="float:left">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="fa fa-solid fa-bars"></span>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Devices">Devices</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="DeviceTypes">DeviceTypes</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Scenarios">Scenarios</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="ScenarioDevices">ScenarioDevices</a>
                                    @if (User.FindFirst("Role").Value == "Root")
                                    {
                                        <a class="dropdown-item" asp-action="Index" asp-controller="AccountManagement">Gerir</a>
                                    }

                                    <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account" asp-route-username="@User.Identity.Name">Mudar Palavra Passe</a>
                                    <a class="dropdown-item" asp-action="Logout" asp-controller="Account">Logout</a>
                                }
                                else
                                {
                                    <a class="dropdown-item" asp-action="Login" asp-controller="Account">Login</a>
                                    <a class="dropdown-item" asp-action="Registration" asp-controller="Account">Registrar</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @* imports View code *@
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2022 - SOA for Safety



        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>