implementation/ICT/ICT.MM.PL.WebAPI/Controllers/DeviceController.cs
using ICT.MM.Core.DTO;
using Microsoft.AspNetCore.Mvc;
using System.Web.Http.Cors;

namespace ICT.MM.PL.WebAPI.Controllers {
    [EnableCors("*","*","*")]
    [ApiController]
    [Route("[controller]")]
    public class DeviceController : ControllerBase {

        [HttpGet(Name = "GetDevices")]
        public ListDeviceResponseDTO GetList()
        {
            return DeviceBLL.ListDevices();
        }

        [HttpDelete(Name = "DeleteDevice")]
        public void DeleteDevice(DeleteDeviceRequestDTO dto)
        {
            DeviceBLL.DeleteDevice(dto);
        }

        [HttpPut(Name = "InsertDevice")]
        public void InsertDevice(InsertDeviceRequestDTO dto)
        {
            DeviceBLL.InsertDevice(dto);
        }

        [HttpPatch(Name = "UpdateDevice")]
        public void UpdateDevice(UpdateDeviceRequestDTO dto)
        {
            DeviceBLL.UpdateDevice(dto);
        }
    }
}

implementation/ICT/ICT.MM.PL.WebAPI/Controllers/DeviceTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICT.MM.DAL.DB;
using Microsoft.AspNetCore.Authorization;

namespace ICT.MM.PL.WebAPI.Controllers
{
    /// <summary>
    /// Controller para os tipos de dispositivos
    /// </summary>
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [Authorize(Policy = "LoggedIn")]
    public class DeviceTypesController : Controller
    {
        private readonly ICTDbContext _context;

        public DeviceTypesController(ICTDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Lista os dispositivos presentes na base de dados
        /// </summary>
        /// <returns></returns>
        // GET: DeviceTypes
        public async Task<IActionResult> Index()
        {
              return _context.DeviceTypes != null ? 
                          View(await _context.DeviceTypes.ToListAsync()) :
                          Problem("Entity set 'ICTDbContext.DeviceTypes'  is null.");
        }

        /// <summary>
        /// Mostra os detalhes de um tipo de dispositivo dado o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: DeviceTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DeviceTypes == null)
            {
                return NotFound();
            }
            //procura na base de dados e retorna a view com a informação do tipo de dispositivo
            var deviceType = await _context.DeviceTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deviceType == null)
            {
                return NotFound();
            }

            return View(deviceType);
        }
        /// <summary>
        /// Retorna a view para criar um novo tipo de dispositivo
        /// </summary>
        /// <returns></returns>
        // GET: DeviceTypes/Create
        [Authorize(Policy = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Cria um novo tipo de dispositivo na base de dados
        /// </summary>
        /// <param name="deviceType"></param>
        /// <returns></returns>
        // POST: DeviceTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] DeviceType deviceType)
        {
            if (ModelState.IsValid)
            {
                //adiciona o novo tipo de dispositivo á base de dados
                _context.Add(deviceType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(deviceType);
        }
        /// <summary>
        /// Retorna a view para editar um tipo de dispositivo
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: DeviceTypes/Edit/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DeviceTypes == null)
            {
                return NotFound();
            }
            //procura na base de dados pelo tipo de dispositivo
            var deviceType = await _context.DeviceTypes.FindAsync(id);
            if (deviceType == null)
            {
                return NotFound();
            }
            return View(deviceType);
        }
        /// <summary>
        /// Atualiza um tipo de dispositivo na base de dados
        /// </summary>
        /// <param name="id"></param>
        /// <param name="deviceType"></param>
        /// <returns></returns>
        // POST: DeviceTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] DeviceType deviceType)
        {
            if (id != deviceType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Atualiza o tipo de dispositivo na base de dados
                    _context.Update(deviceType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceTypeExists(deviceType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deviceType);
        }
        /// <summary>
        /// Retorna a view para o utilizador confirmar a eliminaçao de um tipo de dispositivo
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: DeviceTypes/Delete/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DeviceTypes == null)
            {
                return NotFound();
            }
            //procura na base de dados pelo tipo de dispositivo e retorna a view com essas informações
            var deviceType = await _context.DeviceTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deviceType == null)
            {
                return NotFound();
            }

            return View(deviceType);
        }
        /// <summary>
        /// Elimina um tipo de dispositivo da base de dados dado o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: DeviceTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DeviceTypes == null)
            {
                return Problem("Entity set 'ICTDbContext.DeviceTypes'  is null.");
            }
            //Procura na base de dados pelo tipo de dispositivo e se exitir elimina-o
            var deviceType = await _context.DeviceTypes.FindAsync(id);

            if (deviceType != null)
            {
                _context.DeviceTypes.Remove(deviceType);
            }

            //Procura e elimina da base de dados todos os dispositivo que sejam do tipo que estamos a apagar 
            var devices = _context.Devices.Where(m => m.Id_DeviceType == id).ToList();
            if (devices != null)
            {
                _context.Devices.RemoveRange(devices);
            }

            //Elimina da tabela ScenariosDevices todas a ocorrencias de dispositivos que tenham de ser eliminados
            foreach(Device device in devices)
            {
                if (_context.ScenarioDevices.Where(x => x.Id_Device == device.Id) != null)
                {
                    _context.ScenarioDevices.RemoveRange(_context.ScenarioDevices.Where(x => x.Id_Device == device.Id));
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// Verifica se determinado tipo de dispositivo existe na base de dados dado o seu id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool DeviceTypeExists(int id)
        {
          return (_context.DeviceTypes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

implementation/ICT/ICT.MM.PL.WebAPI/Views/Devices/Create.cshtml
@model ICT.MM.DAL.DB.Device

@{
    ViewData["Title"] = "Create Device";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Novo</h1>

<h4>Dispositivo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DeviceType" class="control-label"></label>
                <select asp-for="Id_DeviceType" class ="form-control" asp-items="ViewBag.Id_DeviceType"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturedDate" class="control-label"></label>
                <input asp-for="ManufacturedDate" class="form-control" />
                <span asp-validation-for="ManufacturedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaintenanceDueDate" class="control-label"></label>
                <input asp-for="MaintenanceDueDate" class="form-control" />
                <span asp-validation-for="MaintenanceDueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturedBy" class="control-label"></label>
                <input asp-for="ManufacturedBy" class="form-control" />
                <span asp-validation-for="ManufacturedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar á Lista</a>
</div>

implementation/ICT/ICT.MM.PL.WebAPI/Views/Devices/Delete.cshtml
@model ICT.MM.DAL.DB.Device

@{
    ViewData["Title"] = "Delete Device";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<h3>Tem certeza de que deseja eliminar este dispositivo?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastMaintenanceDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastMaintenanceDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaintenanceDueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaintenanceDueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeviceType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeviceType.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <br/>
        <a asp-action="Index">Voltar á Lista</a>
    </form>
</div>

implementation/ICT/ICT.MM.PL.WebAPI/Views/Devices/Details.cshtml
@model ICT.MM.DAL.DB.Device

@{
    ViewData["Title"] = "Device Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalhes</h1>

<div>
    <h4>Dispositivos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastMaintenanceDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastMaintenanceDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaintenanceDueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaintenanceDueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufacturedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeviceType)
        </dt>
        <dd class = "col-sm-10">
            <a asp-action="Details" asp-controller="DeviceTypes" asp-route-id="@Model.Id_DeviceType">
                @Html.DisplayFor(model => model.DeviceType.Name)
            </a>
        </dd>
    </dl>
</div>
<div>
    @if ((User.FindFirst("Role").Value == "Admin") || (User.FindFirst("Role").Value == "Root"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a>
        <br />
    }
    <a asp-action="Index">Voltar á Lista</a>
</div>

implementation/ICT/ICT.MM.PL.WebAPI/Views/Devices/Edit.cshtml
@model ICT.MM.DAL.DB.Device

@{
    ViewData["Title"] = "Edit Device";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Dispositivos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="CreatedBy" />
            <input type="hidden" asp-for="ManufacturedDate" />
            <input type="hidden" asp-for="ManufacturedBy" />
            <input type="hidden" asp-for="CreatedDate" />
            <input type="hidden" asp-for="CreatedDate" />

            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Id_DeviceType" class="control-label"></label>
                <select asp-for="Id_DeviceType" class="form-control" asp-items="ViewBag.Id_DeviceType"></select>
                <span asp-validation-for="Id_DeviceType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastMaintenanceDate" class="control-label"></label>
                <input asp-for="LastMaintenanceDate" class="form-control" />
                <span asp-validation-for="LastMaintenanceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaintenanceDueDate" class="control-label"></label>
                <input asp-for="MaintenanceDueDate" class="form-control" />
                <span asp-validation-for="MaintenanceDueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar á Lista</a>
</div>

implementation/ICT/ICT.MM.PL.WebAPI/Views/Devices/Index.cshtml
@model IEnumerable<ICT.MM.DAL.DB.Device>

@{
    ViewData["Title"] = "Devices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Dispositivos</h1>

<p>

    @if ((User.FindFirst("Role").Value == "Admin") || (User.FindFirst("Role").Value == "Root"))
    {

        <a asp-action="Create">Criar Dispositivo</a>
    }
    
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufacturedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastMaintenanceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaintenanceDueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ManufacturedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeviceType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufacturedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastMaintenanceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaintenanceDueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufacturedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>
            <td>
                <a asp-action="Details" asp-controller="DeviceTypes" asp-route-id="@item.Id_DeviceType">
                    @Html.DisplayFor(modelItem => item.DeviceType.Name)
                </a>
            </td>
            <td>
                    @if ((User.FindFirst("Role").Value == "Admin") || (User.FindFirst("Role").Value == "Root")) 
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                     }
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
            </td>
        </tr>
}
    </tbody>
</table>